// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAzKnoidIE6Eo6Mo8RisRnWLpBi7GMv5U',
    appId: '1:712232891207:web:81e1706ac5f2e1fcd7d262',
    messagingSenderId: '712232891207',
    projectId: 'restaurantapp-5d926',
    authDomain: 'restaurantapp-5d926.firebaseapp.com',
    storageBucket: 'restaurantapp-5d926.appspot.com',
    measurementId: 'G-YSEH0ZK3YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKEIbnp04U2F3r6-q0EqhNCrruvgPukSc',
    appId: '1:712232891207:android:bce74bac0acfcea1d7d262',
    messagingSenderId: '712232891207',
    projectId: 'restaurantapp-5d926',
    storageBucket: 'restaurantapp-5d926.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChWu18VKEHskvOu2YxXjFt5hAFaWmdeBY',
    appId: '1:712232891207:ios:14a37f8e6a5d7e02d7d262',
    messagingSenderId: '712232891207',
    projectId: 'restaurantapp-5d926',
    storageBucket: 'restaurantapp-5d926.appspot.com',
    androidClientId: '712232891207-2hkrlr1ni02rmdfr0v7b3pljoggvp5ho.apps.googleusercontent.com',
    iosClientId: '712232891207-pnn2s05ftktadnfgjam2ubq9es6dfpqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.zartemachinetest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChWu18VKEHskvOu2YxXjFt5hAFaWmdeBY',
    appId: '1:712232891207:ios:14a37f8e6a5d7e02d7d262',
    messagingSenderId: '712232891207',
    projectId: 'restaurantapp-5d926',
    storageBucket: 'restaurantapp-5d926.appspot.com',
    androidClientId: '712232891207-2hkrlr1ni02rmdfr0v7b3pljoggvp5ho.apps.googleusercontent.com',
    iosClientId: '712232891207-pnn2s05ftktadnfgjam2ubq9es6dfpqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.zartemachinetest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAzKnoidIE6Eo6Mo8RisRnWLpBi7GMv5U',
    appId: '1:712232891207:web:8ecf8810e4f8af5ad7d262',
    messagingSenderId: '712232891207',
    projectId: 'restaurantapp-5d926',
    authDomain: 'restaurantapp-5d926.firebaseapp.com',
    storageBucket: 'restaurantapp-5d926.appspot.com',
    measurementId: 'G-NYVFTPQ556',
  );

}